#!/usr/bin/env bash
# Verification run: build, tests, code quality and security checks (REQ-120..123).
#
# Runs every check even if one fails, saves each tool's full output under
# docs/evidence/verify/ (with date and tool version) and writes summary.md. Exit code
# is non-zero if any check failed.
#
# Usage:  scripts/verify.sh               # all checks except slow container tests
#         scripts/verify.sh --container   # also build the image and run container tests
#         scripts/verify.sh --offline     # skip checks that need internet (pip-audit, Trivy DB)
#
# Internet: pip-audit and Trivy download current vulnerability data. This is a
# development step, not part of the running service (REQ-012 covers runtime).
# Pinned scanner images (by digest) so results are repeatable:
GITLEAKS_IMAGE="zricethezav/gitleaks@sha256:c00b6bd0aeb3071cbcb79009cb16a60dd9e0a7c60e2be9ab65d25e6bc8abbb7f"  # v8.30.1
TRIVY_IMAGE="aquasec/trivy@sha256:af6acf9a6b85dfe389a1941505c0ce9efef52a4719635e1a962f022a3d855daa"         # 0.75.0

set -uo pipefail
cd "$(dirname "$0")/.."

CONTAINER=0; OFFLINE=0
for arg in "$@"; do
  case "$arg" in
    --container) CONTAINER=1 ;;
    --offline) OFFLINE=1 ;;
    *) echo "unknown option: $arg" >&2; exit 2 ;;
  esac
done

OUT="docs/evidence/verify"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT
mkdir -p "$OUT"
rm -f "$OUT"/*.txt
SUMMARY="$OUT/summary.md"
{
  echo "# Verification summary"
  echo
  # The evidence folder itself is excluded: this run has just deleted its old reports,
  # which would otherwise always count as an uncommitted change.
  echo "Generated by \`scripts/verify.sh $*\` on $(date -u '+%Y-%m-%d %H:%M UTC') at commit \`$(git rev-parse --short HEAD)\`$(git diff --quiet HEAD -- . ":(exclude)$OUT" || echo ' (with uncommitted changes)')."
  echo
  echo "| Check | Requirement | Result | Report |"
  echo "|---|---|---|---|"
} > "$SUMMARY"
FAILED=0

# A shell profile on the development machine sets REQUESTS_CA_BUNDLE to a placeholder
# path, which breaks every HTTPS call made with `requests` (TS-009). Checks run without it.
run() {  # run <name> <requirement> <command...>
  local name="$1" req="$2"; shift 2
  local file="$OUT/$name.txt"
  { echo "\$ $*"; echo "# $(date -u '+%Y-%m-%dT%H:%M:%SZ')"; echo; } > "$file"
  if env -u REQUESTS_CA_BUNDLE "$@" >> "$file" 2>&1; then
    echo "| $name | $req | pass | [$name.txt]($name.txt) |" >> "$SUMMARY"; echo "pass  $name"
  else
    echo "| $name | $req | **FAIL** | [$name.txt]($name.txt) |" >> "$SUMMARY"; echo "FAIL  $name"; FAILED=1
  fi
}
skip() {
  echo "| $1 | $2 | skipped ($3) | - |" >> "$SUMMARY"; echo "skip  $1 ($3)"
}

# --- Tests (REQ-120) ---------------------------------------------------------------
run tests                "REQ-120" uv run pytest -v
if [ "$CONTAINER" = 1 ]; then
  run container-tests    "REQ-120" uv run pytest -m container -v
else
  skip container-tests   "REQ-120" "use --container"
fi

# --- Code quality (REQ-121) ----------------------------------------------------------
run ruff-lint            "REQ-121" uv run ruff check .
run ruff-format          "REQ-121" uv run ruff format --check .
run mypy                 "REQ-121" uv run mypy

# --- Security (REQ-122) ------------------------------------------------------------
run bandit               "REQ-122 static analysis" uv run bandit -c pyproject.toml -r app scripts
run gitleaks-history     "REQ-122 secrets" docker run --rm -v "$PWD:/repo:ro" "$GITLEAKS_IMAGE" git /repo --log-opts=--all --redact --no-banner --no-color
run gitleaks-worktree    "REQ-122 secrets" docker run --rm -v "$PWD:/repo:ro" "$GITLEAKS_IMAGE" dir /repo --redact --no-banner --no-color

if [ "$OFFLINE" = 1 ]; then
  skip pip-audit           "REQ-122 dependencies" "--offline"
  skip trivy-images        "REQ-122 container images (app, jaeger)" "--offline"
else
  uv export --frozen --all-groups --no-emit-project --format requirements-txt > "$WORK/requirements.txt"
  run pip-audit          "REQ-122 dependencies" uv run pip-audit --disable-pip --require-hashes -r "$WORK/requirements.txt"
  # Every image Compose runs is scanned: the app and the Jaeger trace viewer (TS-010).
  # Each image is exported to a file and scanned from there, so the scanner never gets
  # access to the Docker socket. The full report lists every finding; the gate fails
  # only on HIGH/CRITICAL findings that have a fix available (accepted risk: TS-009).
  scan_image() {  # scan_image <name> <image>
    if docker save "$2" -o "$WORK/$1.tar"; then
      run "trivy-$1-report" "REQ-122 $1 image (all findings)" docker run --rm -v "$WORK:/scan:ro" -v elenta-trivy-cache:/root/.cache/trivy "$TRIVY_IMAGE" image --input "/scan/$1.tar" --scanners vuln --no-progress
      run "trivy-$1-gate"   "REQ-122 $1 image (fixable HIGH/CRITICAL)" docker run --rm -v "$WORK:/scan:ro" -v elenta-trivy-cache:/root/.cache/trivy "$TRIVY_IMAGE" image --input "/scan/$1.tar" --scanners vuln --ignore-unfixed --severity HIGH,CRITICAL --exit-code 1 --no-progress
    else
      echo "| trivy-$1 | REQ-122 | **FAIL** (image export) | - |" >> "$SUMMARY"; echo "FAIL  trivy-$1 (image export)"; FAILED=1
    fi
  }
  if docker compose build -q app; then
    scan_image app elenta-ai:local
  else
    echo "| trivy-app | REQ-122 | **FAIL** (image build) | - |" >> "$SUMMARY"; echo "FAIL  image build"; FAILED=1
  fi
  # The Jaeger image reference (tag and digest) is read from compose.yaml, so it is pinned in one place.
  JAEGER_IMAGE="$(sed -n 's/^ *image: *\(jaegertracing\/jaeger:.*\)$/\1/p' compose.yaml)"
  if [ -n "$JAEGER_IMAGE" ] && docker pull -q "$JAEGER_IMAGE" > /dev/null; then
    scan_image jaeger "$JAEGER_IMAGE"
  else
    echo "| trivy-jaeger | REQ-122 | **FAIL** (image not found or pull failed) | - |" >> "$SUMMARY"; echo "FAIL  trivy-jaeger (pull)"; FAILED=1
  fi
fi

{
  echo
  echo "Tool versions: $(uv run ruff --version), $(uv run mypy --version | cut -d' ' -f1-2), bandit $(uv run bandit --version 2>/dev/null | head -1 | awk '{print $2}'), pip-audit $(uv run pip-audit --version | awk '{print $2}'), gitleaks v8.30.1, Trivy 0.75.0, pytest $(uv run pytest --version 2>&1 | awk '{print $2}')."
} >> "$SUMMARY"
echo; echo "summary: $SUMMARY"
exit "$FAILED"
